; tag::types[]
account-role /= "canTokensMint"
             /  "canTokensBurn"
             /  "canTokensCreate"
             /  "canTokensUpdate"
             /  "canTokensAddExtendedInfo"
             /  "canTokensRemoveExtendedInfo"
; end::types[]
