; tag::types[]
word = tstr
idstore-recall-phrase = [2*5 word]
idstore-address = non-anonymous-identity
idstore-credid = bstr
; end::types[]

; tag::store[]
idstore.store@param = {
    ; Recall phrase to be associated to the address and credential ID
    0 => idstore-recall-phrase,

    ; The address associated to the recall phrase
    1 => idstore-address

    ; The credential ID associated to the recall phrase
    2 => idstore-credid
}
idstore.store@return = ()
; end::store[]

; tag::getFromRecallPhrase[]
idstore.getFromRecallPhrase@param = {
    ; The recall phrase to be associated to the credential ID
    0 => idstore-recall-phrase,
}
idstore.idstore.getFromRecallPhrase@return = {
    ; The credential ID
    0 => idstore-credid
}
; end::getFromRecallPhrase[]

; tag::getFromAddress[]
idstore.getFromAddress@param = {
    ; The public address associated to the credential ID
    0 => idstore-address
}

idstore.getFromAddress@return = {
    ; The credential ID
    0 => idstore-credid
}
; end::getFromAddress[]
