; tag::types[]
zip-src = [0, {0: bstr}] ; Zip archive
web-deployment-src = zip-src
web-deployment-info = {
    ; Site name
    0 => tstr,

    ; Site description
    ? 1 => tstr,

    ; Deployment URL
    2 => tstr,
}

web-deployment-filter = [0, {}] ; All
                      / [1, {0: non-anonymous-address}] ; Owner
; end::types[]

; tag::info[]
; `web.info` endpoint.
web.info@param = ()
web.info@return = {
    ; Hash of the current storage state.
    0 => bstr,
}
; end::info[]

; tag::list[]
; `web.list` endpoint.
web.list@param = {
    ; Owner
    ? 0 => non-anonymous-address,

    ; Order
    ? 1 => order,

    ; Filter
    ? 2 => web-deployment-filter,
}
web.list@return = {
    ; List of sites
    0 = [* web-deployment-info],
}
; end::list[]
