; tag::info[]
; Info endpoint.
kvstore.info@param = ()
kvstore.info@return = (info)

info = {
    ; Hash value of the key value state. If two stores have the same hashes,
    ; chances are they have the same values on the same keys (with
    ; some risk of collision).
    ; This can include configuration, depending on the implementation.
    ; The actual hashing method and size of the hash is left to the
    ; implementation.
    0 => bstr,
}
; end::info[]

; tag::get[]
kvstore.get@param = {
    ; The key to get.
    0 => bstr,
}

kvstore.get@return = {
    ; The value directly returned.
    ? 0 => bstr,
}
; end::get[]
