; This attribute exposes hardware informations.

hw-info = {
    ; Processors. All Cores should be reported even if all information are
    ; missing from the CPU description itself.
    0 => [ * processor-info ],

    ; RAM.
    1 => memory-info,
}

; A processor info. All fields are optionals and may not be reported by the
; OS. For example, on some OSes, the CPU speed is 0.
processor-info = {
    ; A system name of this CPU. This can be a string with the core index.
    ? 0 => tstr,

    ; CPU speed in Mhz.
    ? 1 => uint,

    ; Vendor.
    ? 2 => tstr,

    ; Brand / Model.
    ? 3 => tstr,

    ; Usage / Load.
    ? 4 => float32,
}

; Information about the memory (RAM) available to the system.
memory-info = {
    ; Total memory (in bytes).
    ? 0 => uint,

    ; Free memory (in bytes).
    ? 1 => uint,

    ; Available memory (in bytes).
    ? 2 => uint,
}

; Information about the load.
load-info = {
    
}
