; tag::send[]
; Send tokens between two accounts.
ledger.send@param = {
    ; Account that will send the tokens (From).
    ; If omitted, will use the message sender.
    ; The ledger may refuse to send from a different account than
    ; the message sender.
    ? 0 => identity,

    ; The account that will receive the tokens.
    1 => identity,

    ; The amount of tokens to send.
    2 => amount,

    ; The symbol to send.
    3 => symbol,
}
ledger.send@return = ()
; end::send[]
