; tag::status[]
async-result-unknown = 0
async-result-queued = 1
async-result-processing = 2
async-result-done = 3
async-result-expired = 4

async.status@param = {
    ; A token returned by an async attribute.
    ? 0 => bstr,
}
async.status@return =
    ; The token has either never been seen or purged after expiration.
    { 0 => async-result-unknown }

    ; The token is known, but queued for processing later. This step can be skipped
    ; by server that start processing requests immediately.
    / { 0 => async-result-queued }

    ; The token is still being executed but a result isn't known at this point.
    / { 0 => async-result-processing }

    ; The request associated with the token has a result available.
    / {
        0 => async-result-done,
        1 => bstr .cbor response,
    }

    ; A result expired from the local cache and is not available anymore. This is optional
    ; and networks may or may not keep a list of expired tokens.
    / { 0 => async-result-expired }
; end::status[]
