= Identity

Every actor, signer and networks have an identity (materialized in a ManyVerse Address), which is similar to an address in Ethereum.
This identity is represented by a private and public key pair.
The key pair can derive an Address, which may contain additional parts (such as a sub-resource identifier).

== Address

There are multiple types of addresses as part of the ManyVerse;

1. *Anonymous.*
   An anonymous user does not sign messages.
   It's a fixed address that can be used by anyone when sending messages.

2. [[public_key_address]]*Public Key.*
   A public key identity is derived from a public key (itself derived from a private key).
   Its private key MUST sign all messages sent, and its address is a hash of the public key that can validate the signature (see <<_cose_key>>).

3. *Subresource.*
   A Subresource address is an indexed resource inside a network that does not have its own internal public key but can be addressed.
   Messages to and from a subresource should use the same public key as the network they're part of.
   To resolve a public key address from a subresource, use the hash part and build the public key address with its hash.

4. *Invalid.*
   The invalid address does not refer to any identity and cannot sign or validate messages.
   This is a fixed address similar to anonymous, but cannot be used as a source of messages.
   It is however a valid destination and can be used as a target or owner to remove any ownership of resources or assets.
   For example, sending tokens to the invalid address is akin to removing them from the supply (effectively burning them).

=== Binary Format

A ManyVerse Address is a binary buffer of up to 256 bits (32 bytes).
The first 8 bits contain the type of the ID.
The rest depends on the type of address:

[stripes=odd,cols="1,1,1,2"]
|===
3+| Bytes | Description

| Tag (8 bits)
2+| Content (up to 31 bytes)
|

3+| 0x00 (Anonymous)
| Anonymous Address.
  The address field can be omitted for anonymous identities (no bytes).
  If required, the serialization of the anonymous identity is a single null byte.

| 0x01 (Public Key)
2+| SHA-3 (224 bits) of COSE encoded public key (see <<_cose_key>>).
| The address of an identity that has a private key (can sign), and MAY receive messages.
  This can be a user or a network of computers sharing a distributed key.

3+| 0x02 (Invalid)
| Invalid Address.

| 0x80 - 0xFF (Subresource index high bits)
| SHA-3 (224 bits) of COSE encoded public key (see <<_cose_key>>).
| 24 bits subresource index low bits (see description).
| A sub resource that is part of a Public Key identity.
  It can be directly addressed, but is sharing a public key with other resources and with the network itself.
  An example could be a distributed application or smart contract that doesn't have its own key.

  The Subresource ID is; a 1 bit, the lower 7 bits of the address's tag, then the 24 last bits of the address bytes.
  This allows for 31 bits of subresource.
|===

=== Textual Format

The string format for an ManyVerse identity address is the concatenation of:

- the character `m`,
- the base32 encoding (RFC4648 alphabet, all lowercase) of the address binary value itself,
- the first 2 characters of the base32 encoding (RFC4648 alphabet, all lowercase) of the calculated checksum (see below).

The exception is anonymous, which can be reduced to `maa` (no encoding of the address itself).

==== Checksum
The checksum is the CRC16 checksum (polynomial 0xA001, initial value 0x0000, xor 0x0000, with reflection) of the address byte serialization.
Then the Base32 encoding of this checksum is calculated (RFC4648 alphabet, all lowercase), and the first 2 characters of the encoded string is used as checksum in the textual format.

==== Security Considerations
A Base32 character has 32 possible values, or 5 bits of entropy.
Two characters give us 10 bits of entropy, which indicates that two typos on a textual address has a (1 out of 1024)^2 chance of matching, assuming these typos are randomly distributed.

The Checksum therefore should not be considered secure for preventing collisions (e.g. for hashing), but it is only useful when manually entering addresses from the keyboard.
As such, the risk of collision is acceptable in the case of manual data entry.

== Examples
The following addresses can be used as examples:

[stripes=odd]
|===
| Address Binary | Textual Format
| `0x00` (Anonymous) | `maa` or `maaaa`
| `0x02` (Invalid) | `maiyg`
| `0x0100000000000000000000000000000000000000000000000000000000` | `maeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaah`
| `0x8000000000000000000000000000000000000000000000000000000000000000` | `mqaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaayb`
| `0x8000000000000000000000000000000000000000000000000000000000000001` | `mqaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaqac`
| `0x0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D` | `maebagbafaydqqcikbmga2dqpcaireeyuculbogazdinryhito`
| `0x8102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D828384` | `mqebagbafaydqqcikbmga2dqpcaireeyuculbogazdinryhmcqocauk`
|===

== COSE Key

Resolving the address of a COSE Key is simple;

1. Operations MUST NOT contain the `Sign`, `Encrypt`, `Wrap` or `Derive` operations.
2. Any private key parts (e.g. the `D` point in elliptic curves) must be missing.
3. Serialize the COSE Key in its CBOR binary format, using the Canonical CBOR encoding rules (see https://www.rfc-editor.org/rfc/rfc7049#section-3.9[Canonical CBOR]).
4. Calculate the SHA3-224 hash of the resulting blob.
5. Generate a link:#public_key_address[Public Key] Address with the `Key` part the result of the SHA3-224.
