; A delegation certificate. The resolution of the `From` identity must follow
; the same rules as a regular message, for this envelope.
delegation-certificate = COSE_Sign<{
   ; From. The address of the delegated identity (`Alice` in the example).
   0 => address,

   ; To. The address of the identity that can use the above identity (`Bob` in
   ; the example).
   1 => address,

   ; An expiration timestamp. If the system time is past this timestamp,
   ; the certificate is invalid and the server MUST return an error without
   ; opening the envelope further.
   2 => time,

   ; A description or message about this certificate.
   ? 3 => memo,
}>
