= ABCI-MANY Backend Attribute (#1000)
:cddl: ./cddl/

This attribute is advertised when a server supports being run as the backend in an ABCI bridge, as the MANY application.
A MANY server does not guarantee for decentralized security, so if using ABCI as an implementation of the decentralization, the Bridge Attribute must be implemented by the server and its MANY backend should not be exposed to external network.
The server that exposes this attribute should also not be publicly available.

It exposes the following endpoints:

- `abci.beginBlock`.
    Indicates the start of a block.
    Same as ABCI's `BeginBlock` message.
- `abci.commit`.
    Indicates a block is being committed.
    See ABCI's `Commit` message.
- `abci.endBlock`.
- `abci.init`.
- `abci.info`.
- `abci.checkTx`.
    Method controls what transactions get added to a new block
- `abci.nodeInfo`.
    Includes nodes pub Key, latest blockHash, appHash, blockHeight, and time a block is being committed.
- `abci.validatorInfo`.
    Get validator set at a specific height.
- `abci.genesis`.
    Get the genesis file.
- `abci.consensusParams`.
    Get the consensus parameters.
- `abci.consensusState`.
    Indicated the current consensus state, likd start-time, proposal block hash, block proposer info.
- `abci.unconfirmedTx`.
    Retrieves list of unconfirmed transactions.





