= ID Store Attribute (#10)
:cddl: ./cddl/

Servers use this attribute to implement an identity store containing a map of recall phrase to credential ID and a map of public address to credential ID. 
It does not have to be backed by a blockchain (but it MAY be if it implements attribute #1).

A user cannot modify an entry after it is stored.

It exposes the following endpoints:

- <<_store, `idstore.store`>>. Store new recall phrase/credential ID and adress/credential ID maps.
- <<_getfromrecallphrase, `idstore.getFromRecallPhrase`>>. Get the credential ID associated to the given recall phrase.
- <<_getfromaddress, `idstore.getFromAddress`>>. Get the credential ID associated to the given public address.

== Errors
`idstore` servers reserve the following error codes:

- 100001, `existing_entry`.
    The entry key already exists in the storage.
- 100002, `entry_not_found`.
    Storage was unable to find entry.
- 100003, `invalid_identity`.
    The identity is invalid.
- 100004, `invalid_recall_phrase`.
    The number of words should be [2, 5].

== CDDL
=== `store`
[sources,cddl]
----
include::{cddl}/10_idstore.cddl[tag=store]
----

=== `getFromRecallPhrase`
[sources,cddl]
----
include::{cddl}/10_idstore.cddl[tag=getFromRecallPhrase]
----

=== `getFromAddress`
[sources,cddl]
----
include::{cddl}/10_idstore.cddl[tag=getFromAddress]
----

