= Ledger Tokens Management Attribute (#11)
:cddl: ./cddl/

This attribute specifies that a ledger can have tokens managed by an authority.
Without this attribute, tokens are defined at the genesis of the ledger, and cannot be created, minted, or burnt.

Tokens described by this attribute are fungible and well specified.
They would be equivalent to ERC-20 tokens.

A server implementing this attribute SHOULD protect the endpoints described in this form in some way.
For example, endpoints SHOULD error if the sender isn't from a certain address.

== Creating Tokens

One can create new tokens using the `tokens.create` command.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=create]
----

Most of all information for a token can be updated using the `tokens.update` command.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=update]
----

=== Ownerless Tokens

One can update a token to not have an owner by giving ownership to `null` (NOT anonymous).

== Minting and Burning

One can mint new tokens using the `tokens.mint` command.
The ledger instantly mints the new tokens and associates them with given addresses.
Servers MUST return an error if minting the tokens means increasing the total supply over the maximum supply.

One can burn tokens using the `tokens.burn` command. 
The ledger instantly burns the tokens from the given associated addresses.
One can set the token-burning behavior using a parameter.
1. The ledger MUST burn all tokens held by the accounts and leave them empty if the amount of burnt tokens exceeds the amount held by the accounts, OR;
2. The ledger MUST return an error if the number of burnt tokens exceeds the amount held in the account.
A single token-burning behavior can be active at all times.
A server MUST implement all the behaviors listed above.

Servers MAY delay minting and burning (for example, to process them at the end of the day).
In this case, the response should have the async attribute and only resolve when the minting or burning actually occurs.
See xref:../response/1_async.adoc[Async Responses] for more information on asynchronous operations.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=mint]
----

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=burn]
----

== Events
All creation, update, minting and burning must be recorded in the event log.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=events]
----
