= Ledger Tokens Management Attribute (#11)
:cddl: ./cddl/

This attribute specifies that a ledger specifically can have tokens managed by an authority.
By default, without this attribute, tokens are defined at genesis of the ledger, and cannot be created, minted or burnt.

Tokens described by this attribute are fungible and well specified.
They would be equivalent to ERC-20 tokens.

A server implementing this attribute SHOULD protect the endpoints described in this form in some way.
For example, endpoints SHOULD error if the sender isn't from a certain address.

== Creating Tokens

The `tokens.create` endpoint creates a new token.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=create]
----

Most of all information for a token can be updated using the `tokens.update` command.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=update]
----

== Minting and Burning

The `tokens.mint` endpoint mints new tokens in the ledger associated with certain addresses instantly.
Servers MUST return an error if minting the tokens means increasing the total supply over the maximum supply.

The `tokens.burn` endpoint burns new tokens in the ledger associated with certain addresses instantly.
If a certain flag is passed, servers MUST return an error if accounts have fewer tokens than being burnt.
Otherwise, servers MUST burn all tokens in the accounts and leave those accounts empty.

Servers MAY delay minting and burning (for example, to process them in order at the end of the day).
In this case, the command should be async and only resolved when the minting or burning actually occurs.
See xref:../response/1_async.adoc[Async Responses] for more information on asynchronous operations.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=mint]
----

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=burn]
----

== Events
All creation, update, minting and burning must be recorded in the event log.

[sources,cddl]
----
include::{cddl}/11_ledger_tokens.cddl[tag=events]
----
