= Ledger Tokens Mint and Burn Attribute (#12)
:cddl: ./cddl/

This attribute specifies that a ledger can have tokens burnt or minted.
A ledger may implement this attribute but not the token creation attribute, which means that token owners must be declared through other means (like configuration files at genesis).

== Minting and Burning

One can mint new tokens using the `tokens.mint` command.
The ledger instantly mints the new tokens and associates them with given addresses.
Servers MUST return an error if minting the tokens means increasing the total supply over the maximum supply.

One can burn tokens using the `tokens.burn` command.
The ledger instantly burns the tokens from the given associated addresses.
One can set the token-burning behavior using a parameter.
1. The ledger MUST burn all tokens held by the accounts and leave them empty if the amount of burnt tokens exceeds the amount held by the accounts, OR;
2. The ledger MUST return an error if the number of burnt tokens exceeds the amount held in the account.
A single token-burning behavior can be active at all times.
A server MUST implement all the behaviors listed above.

Servers MAY delay minting and burning (for example, to process them at the end of the day).
In this case, the response should have the async attribute and only resolve when the minting or burning actually occurs.
See xref:../response/1_async.adoc[Async Responses] for more information on asynchronous operations.

[sources,cddl]
----
include::{cddl}/12_ledger_mintburn.cddl[tag=mint]
----

[sources,cddl]
----
include::{cddl}/12_ledger_mintburn.cddl[tag=burn]
----

== Events
Token minting and burning MUST be recorded in the event log.

[sources,cddl]
----
include::{cddl}/12_ledger_mintburn.cddl[tag=events]
----
