= Key-Value Store Attribute (#3)
:cddl: ./cddl/

This attribute is used by servers that implements a key value store interface.
It does not have to be behind a blockchain.

It exposes the following endpoints:

- <<_info, `kvstore.info`>>.
    Returns information about this kvstore.
- <<_get, `kvstore.get`>>.
    Returns the value stored at a specific key.
- <<_put, `kvstore.put`>>.
    Sets the value at the specific key.
- <<_delete, `kvstore.delete`>>.
    Delete the value stored at a specific key.

== Errors
The following error codes are reserved for kvstore servers:

- 30001, `key_exists()`.
An entry already exists at this location.

== Keys
Keys are any valid byte string, including NULL characters.
Keys that don't exist should return an empty value.

== Schema
The store MUST NOT do any validation on the schema of values.
They MUST be considered opaque byte string.

Other attributes might add this functionality.

== Info
The `kvstore.info` endpoint returns general information about the kvstore.

[sources,cddl]
----
include::{cddl}/3_kvstore.cddl[tag=info]
----

== Get
The `kvstore.get` endpoint returns the value stored at a specific key.

[sources,cddl]
----
include::{cddl}/3_kvstore.cddl[tag=get]
----

== Put
The `kvstore.put` endpoint sets the value at a specific key.

[sources,cddl]
----
include::{cddl}/7_kvstore_commands.cddl[tag=put]
----

== Delete
The `kvstore.delete` endpoint removes a value at a specific key.

[sources,cddl]
----
include::{cddl}/7_kvstore_commands.cddl[tag=delete]
