#on:
#  - push
#  - pull_request
#
#name: Rust
#
#jobs:
#  build_and_test:
#    name: Reftests build and test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/bin/
#            ~/.cargo/registry/index/
#            ~/.cargo/registry/cache/
#            ~/.cargo/git/db/
#            target/
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          components: clippy, rustfmt
#      - name: Check code formatting
#        uses: actions-rs/cargo@v1
#        with:
#          command: fmt
#          args: --all -- --check
#      - name: Check lints
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: --release --all-targets --all-features -- -D warnings
#      - name: Perform build (--release)
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --release --all-targets --all-features
#      - name: Run tests
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all-targets --all-features
