[package]
name = "reftests-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
quote = "1.0.14"
serde = "1.0.134"
serde_tokenstream = "0.1.3"
syn = "1.0.86"
